# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2022 # Not windows-latest so we at least know what's happening
                        # See https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# @todo:
# - Download/unzip  WinFlexBison into c:\WinFlexBison
# - Add c:\WinFlexBison to %PATH%
# - Get git clone of https://github.com/roel-v/openscad.git into c:\openscad-build
# - Run c:\openscad-build\build_vcpkg.bat
